import { Restaurant, User, Employee, Shift, AvailabilityRequest } from '../types';
import { format, addDays, startOfWeek } from 'date-fns';

const today = new Date();
const currentMonday = startOfWeek(today, { weekStartsOn: 1 });

export const INITIAL_RESTAURANT: Restaurant = {
  id: 'rest-1',
  name: 'Bistro Bella Italian Kitchen',
  address: '742 Evergreen Terrace, Downtown',
  phone: '(555) 382-9100',
  managerName: 'Sarah Jenkins',
  currency: '$',
  openingHours: {
    Monday: { open: '08:00', close: '22:00' },
    Tuesday: { open: '08:00', close: '22:00' },
    Wednesday: { open: '08:00', close: '22:00' },
    Thursday: { open: '08:00', close: '22:00' },
    Friday: { open: '08:00', close: '23:30' },
    Saturday: { open: '08:00', close: '23:30' },
    Sunday: { open: '09:00', close: '21:00' },
  },
};

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    email: 'manager@bistro.com',
    name: 'Sarah Jenkins',
    role: 'Manager',
    restaurantId: 'rest-1',
  },
  {
    id: 'usr-2',
    email: 'alex.rivers@bistro.com',
    name: 'Alex Rivers',
    role: 'Employee',
    restaurantId: 'rest-1',
    employeeId: 'emp-1',
  },
  {
    id: 'usr-3',
    email: 'marco.rossi@bistro.com',
    name: 'Marco Rossi',
    role: 'Employee',
    restaurantId: 'rest-1',
    employeeId: 'emp-2',
  },
  {
    id: 'usr-4',
    email: 'elena.rostova@bistro.com',
    name: 'Elena Rostova',
    role: 'Employee',
    restaurantId: 'rest-1',
    employeeId: 'emp-3',
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    restaurantId: 'rest-1',
    name: 'Alex Rivers',
    email: 'alex.rivers@bistro.com',
    phone: '(555) 123-4567',
    position: 'Waiter',
    secondaryPositions: ['Cashier'],
    employmentType: 'Full-time',
    maxWeeklyHours: 38,
    hourlyRate: 19.5,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    unavailableDays: ['Sunday'],
    status: 'Active',
  },
  {
    id: 'emp-2',
    restaurantId: 'rest-1',
    name: 'Marco Rossi',
    email: 'marco.rossi@bistro.com',
    phone: '(555) 234-5678',
    position: 'Chef',
    secondaryPositions: ['Kitchen staff'],
    employmentType: 'Full-time',
    maxWeeklyHours: 42,
    hourlyRate: 26.0,
    availableDays: ['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    unavailableDays: ['Monday'],
    status: 'Active',
  },
  {
    id: 'emp-3',
    restaurantId: 'rest-1',
    name: 'Elena Rostova',
    email: 'elena.rostova@bistro.com',
    phone: '(555) 345-6789',
    position: 'Cashier',
    secondaryPositions: ['Barista'],
    employmentType: 'Part-time',
    maxWeeklyHours: 25,
    hourlyRate: 17.5,
    availableDays: ['Monday', 'Wednesday', 'Friday', 'Saturday', 'Sunday'],
    unavailableDays: ['Tuesday', 'Thursday'],
    status: 'Active',
  },
  {
    id: 'emp-4',
    restaurantId: 'rest-1',
    name: 'David Chen',
    email: 'david.chen@bistro.com',
    phone: '(555) 456-7890',
    position: 'Barista',
    secondaryPositions: ['Waiter'],
    employmentType: 'Full-time',
    maxWeeklyHours: 35,
    hourlyRate: 18.0,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    unavailableDays: ['Sunday'],
    status: 'Active',
  },
  {
    id: 'emp-5',
    restaurantId: 'rest-1',
    name: 'Maria Santos',
    email: 'maria.santos@bistro.com',
    phone: '(555) 567-8901',
    position: 'Kitchen staff',
    secondaryPositions: ['Chef'],
    employmentType: 'Full-time',
    maxWeeklyHours: 40,
    hourlyRate: 18.5,
    availableDays: ['Monday', 'Tuesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    unavailableDays: ['Wednesday'],
    status: 'Active',
  },
  {
    id: 'emp-6',
    restaurantId: 'rest-1',
    name: 'Jordan Lee',
    email: 'jordan.lee@bistro.com',
    phone: '(555) 678-9012',
    position: 'Waiter',
    secondaryPositions: ['Cashier'],
    employmentType: 'Part-time',
    maxWeeklyHours: 20,
    hourlyRate: 19.0,
    availableDays: ['Friday', 'Saturday', 'Sunday'],
    unavailableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday'],
    status: 'Active',
  },
  {
    id: 'emp-7',
    restaurantId: 'rest-1',
    name: 'Carlos Mendez',
    email: 'carlos.mendez@bistro.com',
    phone: '(555) 789-0123',
    position: 'Chef',
    employmentType: 'Full-time',
    maxWeeklyHours: 40,
    hourlyRate: 25.0,
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    unavailableDays: ['Saturday', 'Sunday'],
    status: 'Active',
  },
];

// Helper to generate dates relative to current Monday
const dateStr = (offsetDays: number) => format(addDays(currentMonday, offsetDays), 'yyyy-MM-dd');

export const INITIAL_SHIFTS: Shift[] = [
  // Monday
  {
    id: 'shift-101',
    restaurantId: 'rest-1',
    date: dateStr(0),
    startTime: '08:00',
    endTime: '16:00',
    position: 'Barista',
    assignedEmployeeId: 'emp-4',
    isPublished: true,
    color: '#3b82f6',
    notes: 'Morning coffee rush & prep',
  },
  {
    id: 'shift-102',
    restaurantId: 'rest-1',
    date: dateStr(0),
    startTime: '10:00',
    endTime: '18:00',
    position: 'Chef',
    assignedEmployeeId: 'emp-7',
    isPublished: true,
    color: '#ef4444',
    notes: 'Lunch service lead',
  },
  {
    id: 'shift-103',
    restaurantId: 'rest-1',
    date: dateStr(0),
    startTime: '11:00',
    endTime: '19:00',
    position: 'Waiter',
    assignedEmployeeId: 'emp-1',
    isPublished: true,
    color: '#10b981',
    notes: 'Main floor seating',
  },
  {
    id: 'shift-104',
    restaurantId: 'rest-1',
    date: dateStr(0),
    startTime: '12:00',
    endTime: '20:00',
    position: 'Kitchen staff',
    assignedEmployeeId: 'emp-5',
    isPublished: true,
    color: '#8b5cf6',
  },

  // Tuesday
  {
    id: 'shift-105',
    restaurantId: 'rest-1',
    date: dateStr(1),
    startTime: '08:00',
    endTime: '16:00',
    position: 'Barista',
    assignedEmployeeId: 'emp-4',
    isPublished: true,
    color: '#3b82f6',
  },
  {
    id: 'shift-106',
    restaurantId: 'rest-1',
    date: dateStr(1),
    startTime: '10:00',
    endTime: '18:00',
    position: 'Chef',
    assignedEmployeeId: 'emp-2',
    isPublished: true,
    color: '#ef4444',
  },
  {
    id: 'shift-107',
    restaurantId: 'rest-1',
    date: dateStr(1),
    startTime: '11:00',
    endTime: '19:00',
    position: 'Waiter',
    assignedEmployeeId: 'emp-1',
    isPublished: true,
    color: '#10b981',
  },

  // Wednesday
  {
    id: 'shift-108',
    restaurantId: 'rest-1',
    date: dateStr(2),
    startTime: '08:00',
    endTime: '16:00',
    position: 'Cashier',
    assignedEmployeeId: 'emp-3',
    isPublished: true,
    color: '#f59e0b',
  },
  {
    id: 'shift-109',
    restaurantId: 'rest-1',
    date: dateStr(2),
    startTime: '12:00',
    endTime: '20:00',
    position: 'Chef',
    assignedEmployeeId: 'emp-2',
    isPublished: true,
    color: '#ef4444',
  },
  {
    id: 'shift-110',
    restaurantId: 'rest-1',
    date: dateStr(2),
    startTime: '12:00',
    endTime: '20:00',
    position: 'Waiter',
    assignedEmployeeId: 'emp-1',
    isPublished: true,
    color: '#10b981',
  },

  // Thursday
  {
    id: 'shift-111',
    restaurantId: 'rest-1',
    date: dateStr(3),
    startTime: '08:00',
    endTime: '16:00',
    position: 'Barista',
    assignedEmployeeId: 'emp-4',
    isPublished: true,
    color: '#3b82f6',
  },
  {
    id: 'shift-112',
    restaurantId: 'rest-1',
    date: dateStr(3),
    startTime: '15:00',
    endTime: '23:00',
    position: 'Chef',
    assignedEmployeeId: 'emp-2',
    isPublished: true,
    color: '#ef4444',
  },
  {
    id: 'shift-113',
    restaurantId: 'rest-1',
    date: dateStr(3),
    startTime: '16:00',
    endTime: '23:00',
    position: 'Waiter',
    assignedEmployeeId: 'emp-1',
    isPublished: true,
    color: '#10b981',
  },

  // Friday Evening (Peak Demand)
  {
    id: 'shift-114',
    restaurantId: 'rest-1',
    date: dateStr(4),
    startTime: '16:00',
    endTime: '23:30',
    position: 'Chef',
    assignedEmployeeId: 'emp-2',
    isPublished: true,
    color: '#ef4444',
    notes: 'Friday dinner service',
  },
  {
    id: 'shift-115',
    restaurantId: 'rest-1',
    date: dateStr(4),
    startTime: '16:00',
    endTime: '23:30',
    position: 'Waiter',
    assignedEmployeeId: 'emp-1',
    isPublished: true,
    color: '#10b981',
  },
  {
    id: 'shift-116',
    restaurantId: 'rest-1',
    date: dateStr(4),
    startTime: '17:00',
    endTime: '23:30',
    position: 'Waiter',
    assignedEmployeeId: 'emp-6',
    isPublished: true,
    color: '#10b981',
  },
  {
    id: 'shift-117',
    restaurantId: 'rest-1',
    date: dateStr(4),
    startTime: '17:00',
    endTime: '23:30',
    position: 'Cashier',
    assignedEmployeeId: 'emp-3',
    isPublished: true,
    color: '#f59e0b',
  },
  {
    id: 'shift-118',
    restaurantId: 'rest-1',
    date: dateStr(4),
    startTime: '16:00',
    endTime: '23:30',
    position: 'Kitchen staff',
    assignedEmployeeId: 'emp-5',
    isPublished: true,
    color: '#8b5cf6',
  },

  // Saturday
  {
    id: 'shift-119',
    restaurantId: 'rest-1',
    date: dateStr(5),
    startTime: '09:00',
    endTime: '17:00',
    position: 'Barista',
    assignedEmployeeId: 'emp-4',
    isPublished: true,
    color: '#3b82f6',
  },
  {
    id: 'shift-120',
    restaurantId: 'rest-1',
    date: dateStr(5),
    startTime: '15:00',
    endTime: '23:30',
    position: 'Chef',
    assignedEmployeeId: 'emp-2',
    isPublished: true,
    color: '#ef4444',
  },
  {
    id: 'shift-121',
    restaurantId: 'rest-1',
    date: dateStr(5),
    startTime: '16:00',
    endTime: '23:30',
    position: 'Waiter',
    assignedEmployeeId: 'emp-6',
    isPublished: true,
    color: '#10b981',
  },

  // Sunday
  {
    id: 'shift-122',
    restaurantId: 'rest-1',
    date: dateStr(6),
    startTime: '09:00',
    endTime: '17:00',
    position: 'Chef',
    assignedEmployeeId: 'emp-2',
    isPublished: true,
    color: '#ef4444',
  },
  {
    id: 'shift-123',
    restaurantId: 'rest-1',
    date: dateStr(6),
    startTime: '10:00',
    endTime: '18:00',
    position: 'Kitchen staff',
    assignedEmployeeId: 'emp-5',
    isPublished: true,
    color: '#8b5cf6',
  },
  {
    id: 'shift-124',
    restaurantId: 'rest-1',
    date: dateStr(6),
    startTime: '12:00',
    endTime: '20:00',
    position: 'Cashier',
    assignedEmployeeId: 'emp-3',
    isPublished: true,
    color: '#f59e0b',
  },
];

export const INITIAL_AVAILABILITY_REQUESTS: AvailabilityRequest[] = [
  {
    id: 'req-1',
    restaurantId: 'rest-1',
    employeeId: 'emp-1',
    employeeName: 'Alex Rivers',
    requestedAvailableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    requestedUnavailableDays: ['Saturday', 'Sunday'],
    requestedMaxHours: 35,
    reason: 'Attending evening culinary classes on weekends.',
    status: 'Pending',
    createdAt: new Date().toISOString(),
  },
];
